[package]
name = "fixed-trancendental"
version = "0.1.0"
authors = ["Peter Goodspeed-Niklaus <peter.r.goodspeedniklaus@gmail.com>"]
edition = "2018"

[dependencies]
fixed = "1.9.0"

[dev-dependencies]
paste = "1.0.5"
rstest = "0.10.0"
